trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
    - repository: self
      type: git
      name: 10038-lnguerra/Prueba_Test
      ref: refs/heads/main  # Verifica que esta sea la rama correcta

steps:
  - checkout: self
    persistCredentials: true

  - task: DotNetCoreCLI@2
    inputs:
      command: 'restore'
      projects: '**/*.csproj'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: '**/*.csproj'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: '**/*.csproj'
      arguments: '--logger trx --results-directory $(Common.TestResultsDirectory)'

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'VSTest'
      testResultsFiles: '$(Common.TestResultsDirectory)/*.trx'
      searchFolder: '$(System.DefaultWorkingDirectory)'
